Add go to top button
JiyaGupta-cs/mytwit pull request #55
Opened 2024-01-24 05:33 UTC by rahat2134

Fix issue : #47 
<img width="486" alt="Screenshot 2024-01-24 at 11 02 59 AM" src="https://github.com/JiyaGupta-cs/mytwit/assets/136263179/a38e6645-8f24-4913-b3d1-898a5dc7662f">

2024-01-24 05:33 UTC, rahat2134 commented
@JiyaGupta-cs please check the pr.

2024-01-25 12:40 UTC, JiyaGupta-cs commented
@rahat2134 It works only when you scroll in the "What's happening section" but not in the Posts section

2024-01-25 13:25 UTC, rahat2134 commented
> @rahat2134 It works only when you scroll in the "What's happening section" but not in the Posts section

@JiyaGupta-cs  i tried too much things to add gototop button on scroll bar but its not working, can you help me. In which folder i need to add component of button, I tried most of website but the button remain on the screen and not in scroll/post section.

2024-02-18 10:38 UTC, varshith257 commented
@rahat2134  It can be resolved by using

> > @rahat2134 It works only when you scroll in the "What's happening section" but not in the Posts section
> 
> @JiyaGupta-cs i tried too much things to add gototop button on scroll bar but its not working, can you help me. In which folder i need to add component of button, I tried most of website but the button remain on the screen and not in scroll/post section.

@rahat2134  This can be resolved by adding a second `useEffect `block  with use  of `EventListener` to the` window` to listen for a scroll  for Posts container

For your reference:  https://stackabuse.com/how-to-scroll-to-top-in-react-with-a-button-component/

2024-02-18 10:41 UTC, JiyaGupta-cs commented
@rahat2134 Will you work on it? Or @varshith257 Do you wish to take up the issue?

2024-02-18 10:42 UTC, rahat2134 commented
@varshith257 go for it.

2024-02-18 10:47 UTC, varshith257 commented
> @rahat2134 Will you work on it? Or @varshith257 Do you wish to take up the issue?

@JiyaGupta-cs Let them work. :) I will provide any guidance if required. Let's ensure their efforts are not in vain and guide them to build progress

2024-02-18 10:58 UTC, varshith257 commented
> @varshith257 go for it.

@rahat2134  Get Spirit it man! You can solve it. You have made efforts to solve it with bit changes you can successfully solve it

2024-02-18 11:07 UTC, varshith257 requested changes
move the whole code in return function into `post-container`.  After changes It could look like : 

```
const Post = ({ displayName, userName, verified, text, image, avatar, location }) => {
  return (
    <div id="posts-container" className='post-container'>
      <div className='post'>
        <div className="post_avatar">
          <img src={avatar} alt="" />
        </div>
        <GoToTopButton />

        <div className="post_body">
          .........................
```

2024-02-18 11:24 UTC, rahat2134 commented on src/components/Button/GoToTopButton.jsx
> +
Bandwidth issue

2024-02-18 11:55 UTC, JiyaGupta-cs commented
@varshith257 ok

2024-02-19 15:48 UTC, JiyaGupta-cs commented
@varshith257 Fix the issue

2024-02-19 15:49 UTC, JiyaGupta-cs commented
@varshith257 Comment on the issue and I will assign you at the issue

2024-02-21 14:37 UTC, varshith257 commented
> @varshith257 Comment on the issue and I will assign you at the issue

@JiyaGupta-cs Mybad! Sorry for the late reply. I am not active here due to exams. Someone has fixed it  let them work

2024-03-02 11:11 UTC, closed without merging